export const exercises = [
  //Shoulders
  {
    value: 'shoulderHeader',
    label: 'Shoulder Exercises',
    isDisabled: true,
  },
  { value: 'shoulder-press', label: 'Dumbell Shoulder Press' },
  { value: 'militar-press', label: 'Militar Shoulder Press' },
  { value: 'lateral-flys', label: 'Shoulder Flys' },
  { value: 'reverse-flys', label: 'Reverse Shoulder Flys' },
  { value: 'arnold-press', label: 'Arnold Shoulder Press' },
  { value: 'frontal-raise', label: 'Frontal Raise' },
  // Chest
  {
    value: 'chestHeader',
    label: 'Chest Exercises',
    isDisabled: true,
  },
  { value: 'bench-press', label: 'Barbell Bench Press' },
  { value: 'bench-press-dumbell', label: 'Dumbell Bench Press' },
  { value: 'inclined-bench-press', label: 'Inclined Barbell Bench Press' },
  {
    value: 'inclined-bench-press-dumbell',
    label: 'Inclined Dumbell Bench Press',
  },
  { value: 'declined-bench-press', label: 'Declined Barbell Bench Press' },
  {
    value: 'declined-bench-press-dumbell',
    label: 'Declined Dumbell Bench Press',
  },
  { value: 'chest-flys', label: 'Chest Flys' },
  { value: 'inclined-chest-flys', label: 'Inclined Chest Flys' },
  { value: 'declined-chest-flys', label: 'Declined Chest Flys' },
  { value: 'chest-pullover', label: 'Pullover' },
  { value: 'cable-chest-flys', label: 'Cable Chest Flys' },
  { value: 'inclined-cable-chest-flys', label: 'Cable Inclined Chest Flys' },
  { value: 'declined-cable-chest-flys', label: 'Cable Declined Chest Flys' },
  { value: 'chest-dip', label: 'Chest Dips' },
  //Tricep
  {
    value: 'tricepHeader',
    label: 'Tricep Exercises',
    isDisabled: true,
  },
  { value: 'skullcrusher', label: 'Skullcrusher' },
  { value: 'close-grip-bench-press', label: 'Close Grip Bench Press' },
  { value: 'tricep-pushdown', label: 'Tricep Pushdown' },
  { value: 'tricep-pushdown-rope', label: 'Rope Tricep Pushdown' },
  { value: 'single-hand-pushdown', label: 'Single Hand Tricep Pushdown' },
  {
    value: 'standing-overhead-extension',
    label: 'Standing Overhead Extension',
  },
  {
    value: 'standing-overhead-extension-cable',
    label: 'Cable Standing Overhead Extension',
  },
  { value: 'laying-dumbell-extension', label: 'Laying Dumbell Extension' },
  {
    value: 'inclined-laying-dumbell-extension',
    label: 'Inclined Laying Dumbell Extension',
  },
  { value: 'tricep-dip', label: 'Tricep Dips' },
  { value: 'tricep-kickback-dumbell', label: 'Tricep Dumbell Kickback' },
  { value: 'tricep-kickback-rope', label: 'Tricep Rope Kickback' },
  //Legs
  {
    value: 'legsHeader',
    label: 'Legs Exercises',
    isDisabled: true,
  },
  { value: 'squat', label: 'Barbell Squats' },
  { value: 'squat-dumbell', label: 'Dumbell' },
  { value: 'machine-squat', label: 'Hack Squat' },
  { value: 'leg-press', label: 'Leg Press' },
  { value: 'deadlift', label: 'Conventional Deadlift' },
  { value: 'romanian-deadlift', label: 'Romanian Deadlift' },
  { value: 'sumo-deadlift', label: 'Sumo Deadlift' },
  { value: 'machine-leg-extension', label: 'Leg Extension' },
  { value: 'leg-curls', label: 'Leg Curls' },

  {
    value: 'bicepsHeader',
    label: 'Biceps Exercises',
    isDisabled: true,
  },
  { value: 'barbell-curl', label: 'Barbell Curl' },
  { value: 'dumbell-curl', label: 'Dumbell Curl' },
  { value: 'ez-bar-preacher-curl', label: 'Ez Bar Preacher Curl' },
  { value: 'dumbell-preacher-curl', label: 'Dumbell Preacher Curl' },
  { value: 'incline-dumbell-curl', label: 'Incline Dumbell Curl' },
  { value: 'cable-curl', label: 'Cable Curl' },
  { value: 'concentration-curl', label: 'Concentration Curl' },
  { value: 'barbell-hammer-curl', label: 'Barbell Hammer Curl' },
  { value: 'dumbell-hammer-curl', label: 'Dumbell Hammer Curl' },
  { value: 'barbell-drag-curl', label: 'Barbell Drag Curl' },
  { value: 'dumbell-drag-curl', label: 'Dumbell Drag Curl' },
];
